"""whatever

Revision ID: 066e1ad87484
Revises: 86c4b24cd22b
Create Date: 2025-08-08 22:56:19.510577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '066e1ad87484'
down_revision: Union[str, Sequence[str], None] = '86c4b24cd22b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_project_featured_asset'), 'project', type_='foreignkey')
    op.create_foreign_key(None, 'project', 'generated_asset', ['featured_asset_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.create_foreign_key(op.f('fk_project_featured_asset'), 'project', 'generated_asset', ['featured_asset_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
