"""Add user_id to GeneratedAsset

Revision ID: 09eb9d5e2ecc
Revises: 845ad7848339
Create Date: 2025-08-05 05:29:23.898689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09eb9d5e2ecc'
down_revision: Union[str, Sequence[str], None] = '845ad7848339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_asset', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'generated_asset', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'generated_asset', type_='foreignkey')
    op.drop_column('generated_asset', 'user_id')
    # ### end Alembic commands ###
