"""Add asset_type relationship

Revision ID: 56cf1069bb62
Revises: ef002e0f03e3
Create Date: 2025-07-27 19:39:45.764313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56cf1069bb62'
down_revision: Union[str, Sequence[str], None] = 'ef002e0f03e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_type',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('generated_asset', sa.Column('format', sa.String(), nullable=True))
    op.add_column('generated_asset', sa.Column('thumbnail_url', sa.String(), nullable=True))
    op.add_column('generated_asset', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('generated_asset', sa.Column('asset_type_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'generated_asset', 'asset_type', ['asset_type_id'], ['id'])
    op.drop_column('generated_asset', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_asset', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'generated_asset', type_='foreignkey')
    op.drop_column('generated_asset', 'asset_type_id')
    op.drop_column('generated_asset', 'file_size')
    op.drop_column('generated_asset', 'thumbnail_url')
    op.drop_column('generated_asset', 'format')
    op.drop_table('asset_type')
    # ### end Alembic commands ###
