"""3 Promt log update

Revision ID: 763ed640cd2a
Revises: ac558c0eaa75
Create Date: 2025-07-27 06:45:56.510075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '763ed640cd2a'
down_revision: Union[str, Sequence[str], None] = 'ac558c0eaa75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt_log', sa.Column('project_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'prompt_log', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prompt_log', type_='foreignkey')
    op.drop_column('prompt_log', 'project_id')
    # ### end Alembic commands ###
