"""add style_json and text_overlays to GeneratedAsset

Revision ID: 845ad7848339
Revises: 56cf1069bb62
Create Date: 2025-08-05 04:40:37.196233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '845ad7848339'
down_revision: Union[str, Sequence[str], None] = '56cf1069bb62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('stripe_price_id', sa.String(), nullable=False),
    sa.Column('monthly_price_cents', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_generations_per_month', sa.Integer(), nullable=False),
    sa.Column('priority_gpu', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('stripe_price_id')
    )
    op.create_table('subscription',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('asset_type_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('preview_url', sa.String(), nullable=True),
    sa.Column('default_prompt', sa.String(), nullable=True),
    sa.Column('style_json', sa.JSON(), nullable=True),
    sa.Column('example_overlay', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_type_id'], ['asset_type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('generated_asset', sa.Column('template_id', sa.UUID(), nullable=True))
    op.add_column('generated_asset', sa.Column('style_json', sa.JSON(), nullable=True))
    op.add_column('generated_asset', sa.Column('text_overlays', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'generated_asset', 'template', ['template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'generated_asset', type_='foreignkey')
    op.drop_column('generated_asset', 'text_overlays')
    op.drop_column('generated_asset', 'style_json')
    op.drop_column('generated_asset', 'template_id')
    op.drop_table('template')
    op.drop_table('subscription')
    op.drop_table('plan')
    # ### end Alembic commands ###
