"""Added Prompt Type wiht links to promts

Revision ID: ca727d58a3e4
Revises: 763ed640cd2a
Create Date: 2025-07-27 16:09:54.497806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca727d58a3e4'
down_revision: Union[str, Sequence[str], None] = '763ed640cd2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_type',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_prompt_type_id'), 'prompt_type', ['id'], unique=False)
    op.add_column('prompt_log', sa.Column('email', sa.String(), nullable=True))
    op.add_column('prompt_log', sa.Column('prompt_type_id', sa.UUID(), nullable=True))
    op.alter_column('prompt_log', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_prompt_log_email'), 'prompt_log', ['email'], unique=False)
    op.create_index(op.f('ix_prompt_log_id'), 'prompt_log', ['id'], unique=False)
    op.create_foreign_key(None, 'prompt_log', 'prompt_type', ['prompt_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prompt_log', type_='foreignkey')
    op.drop_index(op.f('ix_prompt_log_id'), table_name='prompt_log')
    op.drop_index(op.f('ix_prompt_log_email'), table_name='prompt_log')
    op.alter_column('prompt_log', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('prompt_log', 'prompt_type_id')
    op.drop_column('prompt_log', 'email')
    op.drop_index(op.f('ix_prompt_type_id'), table_name='prompt_type')
    op.drop_table('prompt_type')
    # ### end Alembic commands ###
