"""turned keycloak_id into str

Revision ID: e05e496f763f
Revises: e5132119a1b9
Create Date: 2025-08-07 00:02:21.744568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e05e496f763f'
down_revision: Union[str, Sequence[str], None] = 'e5132119a1b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'keycloak_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('user_keycloak_id_key'), 'user', type_='unique')
    op.create_index(op.f('ix_user_keycloak_id'), 'user', ['keycloak_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_keycloak_id'), table_name='user')
    op.create_unique_constraint(op.f('user_keycloak_id_key'), 'user', ['keycloak_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('user', 'keycloak_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
