"""turned user hashed_password into keycloak_id

Revision ID: e5132119a1b9
Revises: 09eb9d5e2ecc
Create Date: 2025-08-06 22:19:15.971173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5132119a1b9'
down_revision: Union[str, Sequence[str], None] = '09eb9d5e2ecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('generated_asset', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('user', sa.Column('keycloak_id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'user', ['keycloak_id'])
    op.drop_column('user', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'keycloak_id')
    op.alter_column('generated_asset', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
