"""Added Tag and Log for project

Revision ID: ef002e0f03e3
Revises: ca727d58a3e4
Create Date: 2025-07-27 17:36:14.658131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef002e0f03e3'
down_revision: Union[str, Sequence[str], None] = 'ca727d58a3e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('status', sa.String(), nullable=False))
    op.add_column('project', sa.Column('description', sa.String(), nullable=True))
    op.add_column('project', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'is_active')
    op.drop_column('project', 'description')
    op.drop_column('project', 'status')
    # ### end Alembic commands ###
