// AUTO-GENERATED by scripts/convert-brushes.mjs — DO NOT EDIT BY HAND
// Source: src/data/brush-import/brush-presets-v1.json
import type { BrushCategory, BrushPreset, BrushParam, BrushParamType } from "@/data/brushPresets";
import type { EngineConfig } from "@/lib/brush/engine";

// local copy of your helper so this file is self-contained
const p = (
  key: BrushParam["key"],
  label: string,
  type: BrushParamType,
  def: number,
  min = 0,
  max = 100,
  step = 1,
  show?: boolean
): BrushParam => ({
  key, label, type, defaultValue: def, min, max, step, ...(show === false ? { show } : {}),
});

export type __Keep = EngineConfig;


export const BRUSH_CATEGORIES: BrushCategory[] = [
  {
    id: "sketching",
    name: "Sketching",
    brushes: [
      {
        id: "peppermint",
        name: "Peppermint",
        
        params: [
          p("size", "Size", "size", 10, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 3, 0, 100, 1),
          p("grain", "Grain", "grain", 52, 0, 100, 1)
        ],
        engine: {
          backend: "stamping",
          strokePath: {"spacing":4,"jitter":2,"scatter":0.4,"streamline":28,"count":1},
          shape: {"type":"oval","angle":8,"softness":50,"roundness":28,"sizeScale":1},
          grain: {"kind":"paper","depth":60,"scale":1.15},
          rendering: {"mode":"glazed","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":0.9,"tipScaleEnd":0.85},
        }
      },
      {
        id: "derwent",
        name: "Derwent",
        
        params: [
          p("size", "Size", "size", 11, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 3, 0, 100, 1),
          p("grain", "Grain", "grain", 52, 0, 100, 1)
        ],
        engine: {
          backend: "stamping",
          strokePath: {"spacing":4,"jitter":2,"scatter":0.4,"streamline":28,"count":1},
          shape: {"type":"oval","angle":8,"softness":50,"roundness":28,"sizeScale":1},
          grain: {"kind":"paper","depth":60,"scale":1.15},
          rendering: {"mode":"glazed","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":0.9,"tipScaleEnd":0.85},
        }
      },
      {
        id: "procreate-pencil",
        name: "Procreate Pencil",
        
        params: [
          p("size", "Size", "size", 12, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 3, 0, 100, 1),
          p("grain", "Grain", "grain", 52, 0, 100, 1)
        ],
        engine: {
          backend: "stamping",
          strokePath: {"spacing":4,"jitter":2,"scatter":0.4,"streamline":28,"count":1},
          shape: {"type":"oval","angle":8,"softness":50,"roundness":28,"sizeScale":1},
          grain: {"kind":"paper","depth":60,"scale":1.15},
          rendering: {"mode":"glazed","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":0.9,"tipScaleEnd":0.85},
        }
      },
      {
        id: "technical-pencil",
        name: "Technical Pencil",
        
        params: [
          p("size", "Size", "size", 8, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 3, 0, 100, 1),
          p("grain", "Grain", "grain", 52, 0, 100, 1)
        ],
        engine: {
          backend: "stamping",
          strokePath: {"spacing":3,"jitter":2,"scatter":0.4,"streamline":28,"count":1},
          shape: {"type":"oval","angle":8,"softness":50,"roundness":28,"sizeScale":1},
          grain: {"kind":"paper","depth":60,"scale":1.15},
          rendering: {"mode":"glazed","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":0.9,"tipScaleEnd":0.85},
        }
      },
      {
        id: "hb-pencil",
        name: "HB Pencil",
        
        params: [
          p("size", "Size", "size", 10, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 3, 0, 100, 1),
          p("grain", "Grain", "grain", 52, 0, 100, 1)
        ],
        engine: {
          backend: "stamping",
          strokePath: {"spacing":4,"jitter":2,"scatter":0.4,"streamline":28,"count":1},
          shape: {"type":"oval","angle":8,"softness":50,"roundness":28,"sizeScale":1},
          grain: {"kind":"paper","depth":60,"scale":1.15},
          rendering: {"mode":"glazed","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":0.9,"tipScaleEnd":0.85},
        }
      },
      {
        id: "6b-pencil",
        name: "6B Pencil",
        
        params: [
          p("size", "Size", "size", 14, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 3, 0, 100, 1),
          p("grain", "Grain", "grain", 52, 0, 100, 1)
        ],
        engine: {
          backend: "stamping",
          strokePath: {"spacing":4,"jitter":2,"scatter":0.4,"streamline":28,"count":1},
          shape: {"type":"oval","angle":8,"softness":50,"roundness":28,"sizeScale":1},
          grain: {"kind":"paper","depth":60,"scale":1.15},
          rendering: {"mode":"glazed","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":0.9,"tipScaleEnd":0.85},
        }
      },
      {
        id: "soft-pencil",
        name: "Soft Pencil",
        
        params: [
          p("size", "Size", "size", 13, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 3, 0, 100, 1),
          p("grain", "Grain", "grain", 52, 0, 100, 1)
        ],
        engine: {
          backend: "stamping",
          strokePath: {"spacing":4,"jitter":3,"scatter":0.5,"streamline":28,"count":1},
          shape: {"type":"oval","angle":8,"softness":50,"roundness":28,"sizeScale":1},
          grain: {"kind":"paper","depth":60,"scale":1.15},
          rendering: {"mode":"glazed","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":0.9,"tipScaleEnd":0.85},
        }
      },
      {
        id: "oil-pastel",
        name: "Oil Pastel",
        
        params: [
          p("size", "Size", "size", 18, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 3, 0, 100, 1),
          p("grain", "Grain", "grain", 52, 0, 100, 1)
        ],
        engine: {
          backend: "stamping",
          strokePath: {"spacing":6,"jitter":8,"scatter":0.8,"streamline":28,"count":1},
          shape: {"type":"oval","angle":8,"softness":50,"roundness":28,"sizeScale":1},
          grain: {"kind":"paper","depth":60,"scale":1.15},
          rendering: {"mode":"glazed","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":0.85,"tipScaleEnd":0.8},
        }
      },
      {
        id: "artist-crayon",
        name: "Artist Crayon",
        
        params: [
          p("size", "Size", "size", 16, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 3, 0, 100, 1),
          p("grain", "Grain", "grain", 52, 0, 100, 1)
        ],
        engine: {
          backend: "stamping",
          strokePath: {"spacing":6,"jitter":6,"scatter":0.8,"streamline":28,"count":1},
          shape: {"type":"oval","angle":8,"softness":50,"roundness":28,"sizeScale":1},
          grain: {"kind":"paper","depth":60,"scale":1.15},
          rendering: {"mode":"glazed","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":0.85,"tipScaleEnd":0.8},
        }
      }
    ]
  },
  {
    id: "inking",
    name: "Inking",
    brushes: [
      {
        id: "mercury",
        name: "Mercury",
        
        params: [
          p("size", "Size", "size", 18, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 3, 0, 100, 1)
        ],
        engine: {
          backend: "stamping",
          strokePath: {"spacing":4,"jitter":0.8,"scatter":0.1,"streamline":30,"count":1},
          shape: {"type":"round","softness":12,"sizeScale":1},
          grain: {"kind":"none","depth":0,"scale":1},
          rendering: {"mode":"glazed","wetEdges":false,"flow":100},
          overrides: {"toothBody":0.06,"toothFlank":0.1,"toothScale":0,"rimMode":"off","uniformity":0.78,"tipScaleStart":0.92,"tipScaleEnd":0.9,"tipMinPx":0.7,"bellyGain":1.02,"edgeNoiseStrength":0},
        }
      },
      {
        id: "inka",
        name: "Inka",
        
        params: [
          p("size", "Size", "size", 14, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 3, 0, 100, 1)
        ],
        engine: {
          backend: "stamping",
          strokePath: {"spacing":4,"jitter":0.8,"scatter":0.1,"streamline":30,"count":1},
          shape: {"type":"round","softness":12,"sizeScale":1},
          grain: {"kind":"none","depth":0,"scale":1},
          rendering: {"mode":"glazed","wetEdges":false,"flow":100},
          overrides: {"toothBody":0.06,"toothFlank":0.1,"toothScale":0,"rimMode":"off","uniformity":0.78,"tipScaleStart":0.92,"tipScaleEnd":0.9,"tipMinPx":0.7,"bellyGain":1.02,"edgeNoiseStrength":0},
        }
      },
      {
        id: "fine-tip",
        name: "Fine Tip",
        
        params: [
          p("size", "Size", "size", 6, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1)
        ],
        engine: {
          backend: "ribbon",
          strokePath: {"spacing":3,"jitter":0.8,"scatter":0.1,"streamline":26,"count":1},
          shape: {"type":"nib","softness":100,"sizeScale":1},
          grain: {"kind":"none","depth":0,"scale":1},
          rendering: {"mode":"marker","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":0.92,"tipScaleEnd":0.9,"tipMinPx":0.7,"uniformity":0.9,"rimMode":"off","toothBody":0,"toothFlank":0},
        }
      },
      {
        id: "technical-pen",
        name: "Technical Pen",
        
        params: [
          p("size", "Size", "size", 10, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1)
        ],
        engine: {
          backend: "ribbon",
          strokePath: {"spacing":3,"jitter":0.8,"scatter":0.1,"streamline":26,"count":1},
          shape: {"type":"nib","softness":100,"sizeScale":1},
          grain: {"kind":"none","depth":0,"scale":1},
          rendering: {"mode":"marker","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":0.92,"tipScaleEnd":0.9,"tipMinPx":0.7,"uniformity":0.9,"rimMode":"off","toothBody":0,"toothFlank":0},
        }
      },
      {
        id: "gel-pen",
        name: "Gel Pen",
        
        params: [
          p("size", "Size", "size", 12, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1)
        ],
        engine: {
          backend: "ribbon",
          strokePath: {"spacing":4,"jitter":0.8,"scatter":0.1,"streamline":26,"count":1},
          shape: {"type":"nib","softness":100,"sizeScale":1},
          grain: {"kind":"none","depth":0,"scale":1},
          rendering: {"mode":"marker","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":0.92,"tipScaleEnd":0.9,"tipMinPx":0.7,"uniformity":0.9,"rimMode":"off","toothBody":0,"toothFlank":0},
        }
      },
      {
        id: "inkbleed",
        name: "Inkbleed",
        
        params: [
          p("size", "Size", "size", 16, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 3, 0, 100, 1)
        ],
        engine: {
          backend: "stamping",
          strokePath: {"spacing":4,"jitter":4,"scatter":1.2,"streamline":30,"count":1},
          shape: {"type":"round","softness":12,"sizeScale":1},
          grain: {"kind":"none","depth":0,"scale":1},
          rendering: {"mode":"glazed","wetEdges":false,"flow":100},
          overrides: {"toothBody":0.06,"toothFlank":0.1,"toothScale":0,"rimMode":"off","uniformity":0.78,"tipScaleStart":0.92,"tipScaleEnd":0.9,"tipMinPx":0.7,"bellyGain":1.02,"edgeNoiseStrength":0},
        }
      },
      {
        id: "studio-pen",
        name: "Studio Pen",
        
        params: [
          p("size", "Size", "size", 16, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1)
        ],
        engine: {
          backend: "ribbon",
          strokePath: {"spacing":4,"jitter":0,"scatter":0.1,"streamline":26,"count":1},
          shape: {"type":"nib","softness":100,"sizeScale":1},
          grain: {"kind":"none","depth":0,"scale":1},
          rendering: {"mode":"marker","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":0.92,"tipScaleEnd":0.9,"tipMinPx":0.7,"uniformity":0.9,"rimMode":"off","toothBody":0,"toothFlank":0},
        }
      },
      {
        id: "dry-ink",
        name: "Dry Ink",
        
        params: [
          p("size", "Size", "size", 15, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 3, 0, 100, 1)
        ],
        engine: {
          backend: "stamping",
          strokePath: {"spacing":4,"jitter":6,"scatter":0.8,"streamline":30,"count":1},
          shape: {"type":"round","softness":12,"sizeScale":1},
          grain: {"kind":"none","depth":0,"scale":1},
          rendering: {"mode":"glazed","wetEdges":false,"flow":100},
          overrides: {"toothBody":0.06,"toothFlank":0.1,"toothScale":0,"rimMode":"off","uniformity":0.78,"tipScaleStart":0.92,"tipScaleEnd":0.9,"tipMinPx":0.7,"bellyGain":1.02,"edgeNoiseStrength":0},
        }
      },
      {
        id: "gesinski-ink",
        name: "Gesinski Ink",
        
        params: [
          p("size", "Size", "size", 20, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 3, 0, 100, 1)
        ],
        engine: {
          backend: "stamping",
          strokePath: {"spacing":4,"jitter":0.8,"scatter":0.1,"streamline":30,"count":1},
          shape: {"type":"round","softness":12,"sizeScale":1},
          grain: {"kind":"none","depth":0,"scale":1},
          rendering: {"mode":"glazed","wetEdges":false,"flow":100},
          overrides: {"toothBody":0.06,"toothFlank":0.1,"toothScale":0,"rimMode":"off","uniformity":0.78,"tipScaleStart":0.92,"tipScaleEnd":0.9,"tipMinPx":0.7,"bellyGain":1.02,"edgeNoiseStrength":0},
        }
      },
      {
        id: "marker",
        name: "Marker",
        
        params: [
          p("size", "Size", "size", 22, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 3, 0, 100, 1)
        ],
        engine: {
          backend: "stamping",
          strokePath: {"spacing":5,"jitter":0.6,"scatter":0.6,"streamline":30,"count":1},
          shape: {"type":"round","softness":12,"sizeScale":1},
          grain: {"kind":"none","depth":0,"scale":1},
          rendering: {"mode":"glazed","wetEdges":false,"flow":100},
          overrides: {"toothBody":0.06,"toothFlank":0.1,"toothScale":0,"rimMode":"off","uniformity":0.78,"tipScaleStart":0.98,"tipScaleEnd":0.98,"tipMinPx":0.7,"bellyGain":1.02,"edgeNoiseStrength":0},
        }
      }
    ]
  },
  {
    id: "dry-media",
    name: "Dry Media (Graphite · Charcoal · Conté)",
    brushes: [
      {
        id: "2b-compressed",
        name: "2B Compressed",
        
        params: [
          p("size", "Size", "size", 18, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 3, 0, 100, 1),
          p("grain", "Grain", "grain", 52, 0, 100, 1)
        ],
        engine: {
          backend: "stamping",
          strokePath: {"spacing":6,"jitter":8,"scatter":0.8,"streamline":24,"count":1},
          shape: {"type":"charcoal","softness":55,"sizeScale":1.1},
          grain: {"kind":"noise","depth":68,"scale":1.25},
          rendering: {"mode":"glazed","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":0.85,"tipScaleEnd":0.8},
        }
      },
      {
        id: "4b-compressed",
        name: "4B Compressed",
        
        params: [
          p("size", "Size", "size", 20, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 3, 0, 100, 1),
          p("grain", "Grain", "grain", 52, 0, 100, 1)
        ],
        engine: {
          backend: "stamping",
          strokePath: {"spacing":6,"jitter":8,"scatter":0.8,"streamline":24,"count":1},
          shape: {"type":"charcoal","softness":55,"sizeScale":1.1},
          grain: {"kind":"noise","depth":68,"scale":1.25},
          rendering: {"mode":"glazed","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":0.85,"tipScaleEnd":0.8},
        }
      },
      {
        id: "6b-compressed",
        name: "6B Compressed",
        
        params: [
          p("size", "Size", "size", 22, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 3, 0, 100, 1),
          p("grain", "Grain", "grain", 52, 0, 100, 1)
        ],
        engine: {
          backend: "stamping",
          strokePath: {"spacing":6,"jitter":8,"scatter":0.8,"streamline":24,"count":1},
          shape: {"type":"charcoal","softness":55,"sizeScale":1.1},
          grain: {"kind":"noise","depth":68,"scale":1.25},
          rendering: {"mode":"glazed","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":0.85,"tipScaleEnd":0.8},
        }
      },
      {
        id: "vine-charcoal",
        name: "Vine Charcoal",
        
        params: [
          p("size", "Size", "size", 18, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 3, 0, 100, 1),
          p("grain", "Grain", "grain", 52, 0, 100, 1)
        ],
        engine: {
          backend: "stamping",
          strokePath: {"spacing":6,"jitter":10,"scatter":1.2,"streamline":24,"count":1},
          shape: {"type":"charcoal","softness":55,"sizeScale":1.1},
          grain: {"kind":"noise","depth":68,"scale":1.25},
          rendering: {"mode":"glazed","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":0.85,"tipScaleEnd":0.8},
        }
      },
      {
        id: "willow-charcoal",
        name: "Willow Charcoal",
        
        params: [
          p("size", "Size", "size", 20, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 3, 0, 100, 1),
          p("grain", "Grain", "grain", 52, 0, 100, 1)
        ],
        engine: {
          backend: "stamping",
          strokePath: {"spacing":6,"jitter":12,"scatter":1.3,"streamline":24,"count":1},
          shape: {"type":"charcoal","softness":55,"sizeScale":1.1},
          grain: {"kind":"noise","depth":68,"scale":1.25},
          rendering: {"mode":"glazed","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":0.85,"tipScaleEnd":0.8},
        }
      },
      {
        id: "carbon-stick",
        name: "Carbon Stick",
        
        params: [
          p("size", "Size", "size", 22, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 3, 0, 100, 1),
          p("grain", "Grain", "grain", 52, 0, 100, 1)
        ],
        engine: {
          backend: "stamping",
          strokePath: {"spacing":6,"jitter":8,"scatter":0.8,"streamline":24,"count":1},
          shape: {"type":"charcoal","softness":55,"sizeScale":1.1},
          grain: {"kind":"noise","depth":68,"scale":1.25},
          rendering: {"mode":"glazed","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":0.85,"tipScaleEnd":0.8},
        }
      },
      {
        id: "charcoal-block",
        name: "Charcoal Block",
        
        params: [
          p("size", "Size", "size", 26, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 3, 0, 100, 1),
          p("grain", "Grain", "grain", 52, 0, 100, 1)
        ],
        engine: {
          backend: "stamping",
          strokePath: {"spacing":6,"jitter":8,"scatter":1.2,"streamline":24,"count":2},
          shape: {"type":"charcoal","softness":55,"sizeScale":1.1},
          grain: {"kind":"noise","depth":68,"scale":1.25},
          rendering: {"mode":"glazed","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":0.85,"tipScaleEnd":0.8},
        }
      },
      {
        id: "burnt-tree",
        name: "Burnt Tree",
        
        params: [
          p("size", "Size", "size", 20, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 3, 0, 100, 1),
          p("grain", "Grain", "grain", 52, 0, 100, 1)
        ],
        engine: {
          backend: "stamping",
          strokePath: {"spacing":6,"jitter":14,"scatter":1.4,"streamline":24,"count":1},
          shape: {"type":"charcoal","softness":55,"sizeScale":1.1},
          grain: {"kind":"noise","depth":68,"scale":1.25},
          rendering: {"mode":"glazed","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":0.85,"tipScaleEnd":0.8},
        }
      }
    ]
  },
  {
    id: "painting",
    name: "Painting",
    brushes: [
      {
        id: "round-brush",
        name: "Round Brush",
        
        params: [
          p("size", "Size", "size", 18, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 3, 0, 100, 1),
          p("grain", "Grain", "grain", 52, 0, 100, 1)
        ],
        engine: {
          backend: "stamping",
          strokePath: {"spacing":5,"jitter":2,"scatter":0.5,"streamline":24,"count":2},
          shape: {"type":"oval","angle":0,"softness":50,"roundness":40,"sizeScale":1},
          grain: {"kind":"canvas","depth":55,"scale":1},
          rendering: {"mode":"blended","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":0.9,"tipScaleEnd":0.88},
        }
      },
      {
        id: "flat-brush",
        name: "Flat Brush",
        
        params: [
          p("size", "Size", "size", 24, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 3, 0, 100, 1),
          p("grain", "Grain", "grain", 52, 0, 100, 1)
        ],
        engine: {
          backend: "stamping",
          strokePath: {"spacing":5,"jitter":2,"scatter":0.5,"streamline":24,"count":3},
          shape: {"type":"oval","angle":0,"softness":50,"roundness":40,"sizeScale":1},
          grain: {"kind":"canvas","depth":55,"scale":1},
          rendering: {"mode":"blended","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":0.9,"tipScaleEnd":0.88},
        }
      },
      {
        id: "acrylic",
        name: "Acrylic",
        
        params: [
          p("size", "Size", "size", 22, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 3, 0, 100, 1),
          p("grain", "Grain", "grain", 52, 0, 100, 1)
        ],
        engine: {
          backend: "stamping",
          strokePath: {"spacing":5,"jitter":2,"scatter":0.8,"streamline":24,"count":3},
          shape: {"type":"oval","angle":0,"softness":50,"roundness":40,"sizeScale":1},
          grain: {"kind":"canvas","depth":55,"scale":1},
          rendering: {"mode":"blended","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":0.9,"tipScaleEnd":0.88},
        }
      },
      {
        id: "wet-acrylic",
        name: "Wet Acrylic",
        
        params: [
          p("size", "Size", "size", 24, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 3, 0, 100, 1),
          p("grain", "Grain", "grain", 52, 0, 100, 1)
        ],
        engine: {
          backend: "stamping",
          strokePath: {"spacing":5,"jitter":4,"scatter":1,"streamline":24,"count":2},
          shape: {"type":"oval","angle":0,"softness":50,"roundness":40,"sizeScale":1},
          grain: {"kind":"canvas","depth":55,"scale":1},
          rendering: {"mode":"blended","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":0.9,"tipScaleEnd":0.88},
        }
      },
      {
        id: "jagged-brush",
        name: "Jagged Brush",
        
        params: [
          p("size", "Size", "size", 20, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 3, 0, 100, 1),
          p("grain", "Grain", "grain", 52, 0, 100, 1)
        ],
        engine: {
          backend: "stamping",
          strokePath: {"spacing":5,"jitter":8,"scatter":1.2,"streamline":24,"count":1},
          shape: {"type":"oval","angle":0,"softness":50,"roundness":40,"sizeScale":1},
          grain: {"kind":"canvas","depth":55,"scale":1},
          rendering: {"mode":"blended","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":0.9,"tipScaleEnd":0.88},
        }
      },
      {
        id: "salamanca",
        name: "Salamanca",
        
        params: [
          p("size", "Size", "size", 20, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 3, 0, 100, 1),
          p("grain", "Grain", "grain", 52, 0, 100, 1)
        ],
        engine: {
          backend: "stamping",
          strokePath: {"spacing":5,"jitter":2,"scatter":0.5,"streamline":24,"count":2},
          shape: {"type":"oval","angle":0,"softness":50,"roundness":40,"sizeScale":1},
          grain: {"kind":"canvas","depth":55,"scale":1},
          rendering: {"mode":"blended","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":0.9,"tipScaleEnd":0.88},
        }
      },
      {
        id: "nikko-rull",
        name: "Nikko Rull",
        
        params: [
          p("size", "Size", "size", 22, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 3, 0, 100, 1),
          p("grain", "Grain", "grain", 52, 0, 100, 1)
        ],
        engine: {
          backend: "stamping",
          strokePath: {"spacing":5,"jitter":5,"scatter":1,"streamline":24,"count":2},
          shape: {"type":"oval","angle":0,"softness":50,"roundness":40,"sizeScale":1},
          grain: {"kind":"canvas","depth":55,"scale":1},
          rendering: {"mode":"blended","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":0.9,"tipScaleEnd":0.88},
        }
      },
      {
        id: "spectra",
        name: "Spectra",
        
        params: [
          p("size", "Size", "size", 18, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 3, 0, 100, 1),
          p("grain", "Grain", "grain", 52, 0, 100, 1)
        ],
        engine: {
          backend: "stamping",
          strokePath: {"spacing":5,"jitter":2,"scatter":0.5,"streamline":24,"count":1},
          shape: {"type":"oval","angle":0,"softness":50,"roundness":40,"sizeScale":1},
          grain: {"kind":"canvas","depth":55,"scale":1},
          rendering: {"mode":"blended","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":0.9,"tipScaleEnd":0.88},
        }
      },
      {
        id: "tamar",
        name: "Tamar",
        
        params: [
          p("size", "Size", "size", 16, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 3, 0, 100, 1),
          p("grain", "Grain", "grain", 52, 0, 100, 1)
        ],
        engine: {
          backend: "stamping",
          strokePath: {"spacing":5,"jitter":3,"scatter":0.5,"streamline":24,"count":2},
          shape: {"type":"oval","angle":0,"softness":50,"roundness":40,"sizeScale":1},
          grain: {"kind":"canvas","depth":55,"scale":1},
          rendering: {"mode":"blended","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":0.9,"tipScaleEnd":0.88},
        }
      },
      {
        id: "old-brush",
        name: "Old Brush",
        
        params: [
          p("size", "Size", "size", 18, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 3, 0, 100, 1),
          p("grain", "Grain", "grain", 52, 0, 100, 1)
        ],
        engine: {
          backend: "stamping",
          strokePath: {"spacing":5,"jitter":10,"scatter":1.1,"streamline":24,"count":2},
          shape: {"type":"oval","angle":0,"softness":50,"roundness":40,"sizeScale":1},
          grain: {"kind":"canvas","depth":55,"scale":1},
          rendering: {"mode":"blended","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":0.9,"tipScaleEnd":0.88},
        }
      },
      {
        id: "dry-brush",
        name: "Dry Brush",
        
        params: [
          p("size", "Size", "size", 18, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 3, 0, 100, 1),
          p("grain", "Grain", "grain", 52, 0, 100, 1)
        ],
        engine: {
          backend: "stamping",
          strokePath: {"spacing":5,"jitter":12,"scatter":1.3,"streamline":24,"count":1},
          shape: {"type":"oval","angle":0,"softness":50,"roundness":40,"sizeScale":1},
          grain: {"kind":"canvas","depth":55,"scale":1},
          rendering: {"mode":"blended","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":0.9,"tipScaleEnd":0.88},
        }
      },
      {
        id: "stucco",
        name: "Stucco",
        
        params: [
          p("size", "Size", "size", 22, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 3, 0, 100, 1),
          p("grain", "Grain", "grain", 52, 0, 100, 1)
        ],
        engine: {
          backend: "stamping",
          strokePath: {"spacing":8,"jitter":15,"scatter":1.2,"streamline":24,"count":2},
          shape: {"type":"oval","angle":0,"softness":50,"roundness":40,"sizeScale":1},
          grain: {"kind":"canvas","depth":55,"scale":1},
          rendering: {"mode":"blended","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":1,"tipScaleEnd":1},
        }
      },
      {
        id: "oil-paint",
        name: "Oil Paint",
        
        params: [
          p("size", "Size", "size", 26, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 3, 0, 100, 1),
          p("grain", "Grain", "grain", 52, 0, 100, 1)
        ],
        engine: {
          backend: "stamping",
          strokePath: {"spacing":5,"jitter":2,"scatter":0.5,"streamline":24,"count":4},
          shape: {"type":"oval","angle":0,"softness":50,"roundness":40,"sizeScale":1},
          grain: {"kind":"canvas","depth":55,"scale":1},
          rendering: {"mode":"blended","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":0.9,"tipScaleEnd":0.88},
        }
      },
      {
        id: "turpentine",
        name: "Turpentine",
        
        params: [
          p("size", "Size", "size", 20, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("grain", "Grain", "grain", 52, 0, 100, 1)
        ],
        engine: {
          backend: "wet",
          strokePath: {"spacing":5,"jitter":2,"scatter":1.2,"streamline":35,"count":2},
          shape: {"type":"round","softness":70,"sizeScale":1.2},
          grain: {"kind":"paper","depth":35,"scale":1.1},
          rendering: {"mode":"wet","wetEdges":true,"flow":60},
          overrides: {"tipScaleStart":0.9,"tipScaleEnd":0.88},
        }
      },
      {
        id: "gouache",
        name: "Gouache",
        
        params: [
          p("size", "Size", "size", 22, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 3, 0, 100, 1),
          p("grain", "Grain", "grain", 52, 0, 100, 1)
        ],
        engine: {
          backend: "stamping",
          strokePath: {"spacing":5,"jitter":2,"scatter":0.5,"streamline":24,"count":2},
          shape: {"type":"oval","angle":0,"softness":50,"roundness":40,"sizeScale":1},
          grain: {"kind":"canvas","depth":55,"scale":1},
          rendering: {"mode":"blended","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":0.9,"tipScaleEnd":0.88},
        }
      },
      {
        id: "fresco",
        name: "Fresco",
        
        params: [
          p("size", "Size", "size", 26, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 3, 0, 100, 1),
          p("grain", "Grain", "grain", 52, 0, 100, 1)
        ],
        engine: {
          backend: "stamping",
          strokePath: {"spacing":8,"jitter":8,"scatter":1.4,"streamline":24,"count":2},
          shape: {"type":"oval","angle":0,"softness":50,"roundness":40,"sizeScale":1},
          grain: {"kind":"canvas","depth":55,"scale":1},
          rendering: {"mode":"blended","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":1,"tipScaleEnd":1},
        }
      },
      {
        id: "watercolor",
        name: "Watercolor",
        
        params: [
          p("size", "Size", "size", 22, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("grain", "Grain", "grain", 52, 0, 100, 1)
        ],
        engine: {
          backend: "wet",
          strokePath: {"spacing":5,"jitter":2,"scatter":1.1,"streamline":35,"count":3},
          shape: {"type":"round","softness":70,"sizeScale":1.2},
          grain: {"kind":"paper","depth":35,"scale":1.1},
          rendering: {"mode":"wet","wetEdges":true,"flow":60},
          overrides: {"tipScaleStart":0.9,"tipScaleEnd":0.88},
        }
      }
    ]
  },
  {
    id: "airbrushing",
    name: "Airbrushing",
    brushes: [
      {
        id: "soft-airbrush",
        name: "Soft Airbrush",
        
        params: [
          p("size", "Size", "size", 28, 1, 160, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 8, 0, 100, 1)
        ],
        engine: {
          backend: "spray",
          strokePath: {"spacing":3,"jitter":0,"scatter":0,"streamline":24,"count":1},
          shape: {"type":"spray","softness":50,"sizeScale":1},
          grain: {"kind":"none","depth":0,"scale":1},
          rendering: {"mode":"spray","wetEdges":false,"flow":55},
          
        }
      },
      {
        id: "medium-airbrush",
        name: "Medium Airbrush",
        
        params: [
          p("size", "Size", "size", 22, 1, 160, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 8, 0, 100, 1)
        ],
        engine: {
          backend: "spray",
          strokePath: {"spacing":3,"jitter":0,"scatter":0,"streamline":24,"count":1},
          shape: {"type":"spray","softness":50,"sizeScale":1},
          grain: {"kind":"none","depth":0,"scale":1},
          rendering: {"mode":"spray","wetEdges":false,"flow":55},
          
        }
      },
      {
        id: "hard-airbrush",
        name: "Hard Airbrush",
        
        params: [
          p("size", "Size", "size", 18, 1, 160, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 8, 0, 100, 1)
        ],
        engine: {
          backend: "spray",
          strokePath: {"spacing":3,"jitter":0,"scatter":0,"streamline":24,"count":1},
          shape: {"type":"spray","softness":50,"sizeScale":1},
          grain: {"kind":"none","depth":0,"scale":1},
          rendering: {"mode":"spray","wetEdges":false,"flow":55},
          
        }
      },
      {
        id: "ultra-fine-nozzle",
        name: "Ultra Fine Nozzle",
        
        params: [
          p("size", "Size", "size", 10, 1, 160, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 8, 0, 100, 1)
        ],
        engine: {
          backend: "spray",
          strokePath: {"spacing":3,"jitter":0,"scatter":0,"streamline":24,"count":1},
          shape: {"type":"spray","softness":50,"sizeScale":1},
          grain: {"kind":"none","depth":0,"scale":1},
          rendering: {"mode":"spray","wetEdges":false,"flow":55},
          
        }
      },
      {
        id: "fine-nozzle",
        name: "Fine Nozzle",
        
        params: [
          p("size", "Size", "size", 14, 1, 160, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 8, 0, 100, 1)
        ],
        engine: {
          backend: "spray",
          strokePath: {"spacing":3,"jitter":0,"scatter":0,"streamline":24,"count":1},
          shape: {"type":"spray","softness":50,"sizeScale":1},
          grain: {"kind":"none","depth":0,"scale":1},
          rendering: {"mode":"spray","wetEdges":false,"flow":55},
          
        }
      },
      {
        id: "medium-nozzle",
        name: "Medium Nozzle",
        
        params: [
          p("size", "Size", "size", 18, 1, 160, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 8, 0, 100, 1)
        ],
        engine: {
          backend: "spray",
          strokePath: {"spacing":3,"jitter":0,"scatter":0,"streamline":24,"count":1},
          shape: {"type":"spray","softness":50,"sizeScale":1},
          grain: {"kind":"none","depth":0,"scale":1},
          rendering: {"mode":"spray","wetEdges":false,"flow":55},
          
        }
      },
      {
        id: "fat-nozzle",
        name: "Fat Nozzle",
        
        params: [
          p("size", "Size", "size", 26, 1, 160, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 8, 0, 100, 1)
        ],
        engine: {
          backend: "spray",
          strokePath: {"spacing":3,"jitter":0,"scatter":0,"streamline":24,"count":1},
          shape: {"type":"spray","softness":50,"sizeScale":1},
          grain: {"kind":"none","depth":0,"scale":1},
          rendering: {"mode":"spray","wetEdges":false,"flow":55},
          
        }
      },
      {
        id: "splatter",
        name: "Splatter",
        
        params: [
          p("size", "Size", "size", 22, 1, 160, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 8, 0, 100, 1)
        ],
        engine: {
          backend: "spray",
          strokePath: {"spacing":3,"jitter":0,"scatter":0,"streamline":24,"count":1},
          shape: {"type":"spray","softness":50,"sizeScale":1},
          grain: {"kind":"none","depth":0,"scale":1},
          rendering: {"mode":"spray","wetEdges":false,"flow":55},
          
        }
      },
      {
        id: "flicks",
        name: "Flicks",
        
        params: [
          p("size", "Size", "size", 18, 1, 160, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 8, 0, 100, 1)
        ],
        engine: {
          backend: "spray",
          strokePath: {"spacing":3,"jitter":0,"scatter":0,"streamline":24,"count":1},
          shape: {"type":"spray","softness":50,"sizeScale":1},
          grain: {"kind":"none","depth":0,"scale":1},
          rendering: {"mode":"spray","wetEdges":false,"flow":55},
          
        }
      },
      {
        id: "burst",
        name: "Burst",
        
        params: [
          p("size", "Size", "size", 20, 1, 160, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 8, 0, 100, 1)
        ],
        engine: {
          backend: "spray",
          strokePath: {"spacing":3,"jitter":0,"scatter":0,"streamline":24,"count":1},
          shape: {"type":"spray","softness":50,"sizeScale":1},
          grain: {"kind":"none","depth":0,"scale":1},
          rendering: {"mode":"spray","wetEdges":false,"flow":55},
          
        }
      },
      {
        id: "drip",
        name: "Drip",
        
        params: [
          p("size", "Size", "size", 24, 1, 160, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 8, 0, 100, 1)
        ],
        engine: {
          backend: "spray",
          strokePath: {"spacing":3,"jitter":0,"scatter":0,"streamline":24,"count":1},
          shape: {"type":"spray","softness":50,"sizeScale":1},
          grain: {"kind":"none","depth":0,"scale":1},
          rendering: {"mode":"spray","wetEdges":false,"flow":55},
          
        }
      },
      {
        id: "smoke",
        name: "Smoke",
        
        params: [
          p("size", "Size", "size", 26, 1, 160, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 8, 0, 100, 1)
        ],
        engine: {
          backend: "spray",
          strokePath: {"spacing":3,"jitter":0,"scatter":0,"streamline":24,"count":1},
          shape: {"type":"spray","softness":50,"sizeScale":1},
          grain: {"kind":"none","depth":0,"scale":1},
          rendering: {"mode":"spray","wetEdges":false,"flow":55},
          
        }
      },
      {
        id: "flames",
        name: "Flames",
        
        params: [
          p("size", "Size", "size", 24, 1, 160, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 8, 0, 100, 1)
        ],
        engine: {
          backend: "spray",
          strokePath: {"spacing":3,"jitter":0,"scatter":0,"streamline":24,"count":1},
          shape: {"type":"spray","softness":50,"sizeScale":1},
          grain: {"kind":"none","depth":0,"scale":1},
          rendering: {"mode":"spray","wetEdges":false,"flow":55},
          
        }
      },
      {
        id: "water",
        name: "Water",
        
        params: [
          p("size", "Size", "size", 22, 1, 160, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 8, 0, 100, 1)
        ],
        engine: {
          backend: "spray",
          strokePath: {"spacing":7,"jitter":15,"scatter":1.2,"streamline":24,"count":2},
          shape: {"type":"spray","softness":50,"sizeScale":1},
          grain: {"kind":"none","depth":0,"scale":1},
          rendering: {"mode":"spray","wetEdges":false,"flow":55},
          overrides: {"tipScaleStart":1,"tipScaleEnd":1},
        }
      },
      {
        id: "oceans",
        name: "Oceans",
        
        params: [
          p("size", "Size", "size", 22, 1, 160, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 8, 0, 100, 1)
        ],
        engine: {
          backend: "spray",
          strokePath: {"spacing":6,"jitter":15,"scatter":1.2,"streamline":24,"count":2},
          shape: {"type":"spray","softness":50,"sizeScale":1},
          grain: {"kind":"none","depth":0,"scale":1},
          rendering: {"mode":"spray","wetEdges":false,"flow":55},
          overrides: {"tipScaleStart":1,"tipScaleEnd":1},
        }
      },
      {
        id: "driven-snow",
        name: "Driven Snow",
        
        params: [
          p("size", "Size", "size", 14, 1, 160, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 8, 0, 100, 1)
        ],
        engine: {
          backend: "spray",
          strokePath: {"spacing":3,"jitter":0,"scatter":0,"streamline":24,"count":1},
          shape: {"type":"spray","softness":50,"sizeScale":1},
          grain: {"kind":"none","depth":0,"scale":1},
          rendering: {"mode":"spray","wetEdges":false,"flow":55},
          
        }
      },
      {
        id: "hard-rain",
        name: "Hard Rain",
        
        params: [
          p("size", "Size", "size", 18, 1, 160, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 8, 0, 100, 1)
        ],
        engine: {
          backend: "spray",
          strokePath: {"spacing":3,"jitter":0,"scatter":0,"streamline":24,"count":1},
          shape: {"type":"spray","softness":50,"sizeScale":1},
          grain: {"kind":"none","depth":0,"scale":1},
          rendering: {"mode":"spray","wetEdges":false,"flow":55},
          
        }
      },
      {
        id: "crystals",
        name: "Crystals",
        
        params: [
          p("size", "Size", "size", 20, 1, 160, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 8, 0, 100, 1)
        ],
        engine: {
          backend: "spray",
          strokePath: {"spacing":3,"jitter":0,"scatter":0,"streamline":24,"count":1},
          shape: {"type":"spray","softness":50,"sizeScale":1},
          grain: {"kind":"none","depth":0,"scale":1},
          rendering: {"mode":"spray","wetEdges":false,"flow":55},
          
        }
      },
      {
        id: "clouds",
        name: "Clouds",
        
        params: [
          p("size", "Size", "size", 28, 1, 160, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 8, 0, 100, 1)
        ],
        engine: {
          backend: "spray",
          strokePath: {"spacing":3,"jitter":0,"scatter":0,"streamline":24,"count":1},
          shape: {"type":"spray","softness":50,"sizeScale":1},
          grain: {"kind":"none","depth":0,"scale":1},
          rendering: {"mode":"spray","wetEdges":false,"flow":55},
          
        }
      }
    ]
  },
  {
    id: "textures",
    name: "Textures",
    brushes: [
      {
        id: "grid",
        name: "Grid",
        
        params: [
          p("size", "Size", "size", 20, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("grain", "Grain", "grain", 52, 0, 100, 1)
        ],
        engine: {
          backend: "pattern",
          strokePath: {"spacing":10,"jitter":0,"scatter":0,"streamline":24,"count":1},
          shape: {"type":"square","softness":10,"sizeScale":1},
          grain: {"kind":"paper","depth":0,"scale":1,"rotate":0},
          rendering: {"mode":"marker","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":1,"tipScaleEnd":1},
        }
      },
      {
        id: "decimals",
        name: "Decimals",
        
        params: [
          p("size", "Size", "size", 20, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("grain", "Grain", "grain", 52, 0, 100, 1)
        ],
        engine: {
          backend: "pattern",
          strokePath: {"spacing":10,"jitter":0,"scatter":0,"streamline":24,"count":1},
          shape: {"type":"square","softness":10,"sizeScale":1},
          grain: {"kind":"paper","depth":0,"scale":1,"rotate":0},
          rendering: {"mode":"marker","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":1,"tipScaleEnd":1},
        }
      },
      {
        id: "diagonal",
        name: "Diagonal",
        
        params: [
          p("size", "Size", "size", 22, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("grain", "Grain", "grain", 52, 0, 100, 1)
        ],
        engine: {
          backend: "pattern",
          strokePath: {"spacing":10,"jitter":0,"scatter":0,"streamline":24,"count":1},
          shape: {"type":"square","softness":10,"sizeScale":1},
          grain: {"kind":"paper","depth":0,"scale":1,"rotate":0},
          rendering: {"mode":"marker","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":1,"tipScaleEnd":1},
        }
      },
      {
        id: "victorian",
        name: "Victorian",
        
        params: [
          p("size", "Size", "size", 20, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("grain", "Grain", "grain", 52, 0, 100, 1)
        ],
        engine: {
          backend: "pattern",
          strokePath: {"spacing":8,"jitter":15,"scatter":1.2,"streamline":24,"count":2},
          shape: {"type":"square","softness":10,"sizeScale":1},
          grain: {"kind":"paper","depth":0,"scale":1,"rotate":0},
          rendering: {"mode":"marker","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":1,"tipScaleEnd":1},
        }
      },
      {
        id: "wood",
        name: "Wood",
        
        params: [
          p("size", "Size", "size", 22, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("grain", "Grain", "grain", 52, 0, 100, 1)
        ],
        engine: {
          backend: "pattern",
          strokePath: {"spacing":8,"jitter":15,"scatter":1.2,"streamline":24,"count":2},
          shape: {"type":"square","softness":10,"sizeScale":1},
          grain: {"kind":"paper","depth":0,"scale":1,"rotate":0},
          rendering: {"mode":"marker","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":1,"tipScaleEnd":1},
        }
      },
      {
        id: "cubes",
        name: "Cubes",
        
        params: [
          p("size", "Size", "size", 20, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("grain", "Grain", "grain", 52, 0, 100, 1)
        ],
        engine: {
          backend: "pattern",
          strokePath: {"spacing":8,"jitter":15,"scatter":1.2,"streamline":24,"count":2},
          shape: {"type":"square","softness":10,"sizeScale":1},
          grain: {"kind":"paper","depth":0,"scale":1,"rotate":0},
          rendering: {"mode":"marker","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":1,"tipScaleEnd":1},
        }
      },
      {
        id: "rosette",
        name: "Rosette",
        
        params: [
          p("size", "Size", "size", 20, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("grain", "Grain", "grain", 52, 0, 100, 1)
        ],
        engine: {
          backend: "pattern",
          strokePath: {"spacing":10,"jitter":0,"scatter":0,"streamline":24,"count":1},
          shape: {"type":"square","softness":10,"sizeScale":1},
          grain: {"kind":"paper","depth":0,"scale":1,"rotate":0},
          rendering: {"mode":"marker","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":1,"tipScaleEnd":1},
        }
      },
      {
        id: "grunge",
        name: "Grunge",
        
        params: [
          p("size", "Size", "size", 24, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("grain", "Grain", "grain", 52, 0, 100, 1)
        ],
        engine: {
          backend: "pattern",
          strokePath: {"spacing":8,"jitter":18,"scatter":1.6,"streamline":24,"count":2},
          shape: {"type":"square","softness":10,"sizeScale":1},
          grain: {"kind":"paper","depth":0,"scale":1,"rotate":0},
          rendering: {"mode":"marker","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":1,"tipScaleEnd":1},
        }
      },
      {
        id: "newsprint",
        name: "Newsprint",
        
        params: [
          p("size", "Size", "size", 20, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("grain", "Grain", "grain", 52, 0, 100, 1)
        ],
        engine: {
          backend: "pattern",
          strokePath: {"spacing":10,"jitter":0,"scatter":0,"streamline":24,"count":1},
          shape: {"type":"square","softness":10,"sizeScale":1},
          grain: {"kind":"paper","depth":0,"scale":1,"rotate":0},
          rendering: {"mode":"marker","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":1,"tipScaleEnd":1},
        }
      },
      {
        id: "buzz",
        name: "Buzz",
        
        params: [
          p("size", "Size", "size", 20, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("grain", "Grain", "grain", 52, 0, 100, 1)
        ],
        engine: {
          backend: "pattern",
          strokePath: {"spacing":8,"jitter":15,"scatter":1.2,"streamline":24,"count":2},
          shape: {"type":"square","softness":10,"sizeScale":1},
          grain: {"kind":"paper","depth":0,"scale":1,"rotate":0},
          rendering: {"mode":"marker","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":1,"tipScaleEnd":1},
        }
      },
      {
        id: "disco",
        name: "Disco",
        
        params: [
          p("size", "Size", "size", 22, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("grain", "Grain", "grain", 52, 0, 100, 1)
        ],
        engine: {
          backend: "pattern",
          strokePath: {"spacing":8,"jitter":15,"scatter":1.2,"streamline":24,"count":2},
          shape: {"type":"square","softness":10,"sizeScale":1},
          grain: {"kind":"paper","depth":0,"scale":1,"rotate":0},
          rendering: {"mode":"marker","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":1,"tipScaleEnd":1},
        }
      },
      {
        id: "flower-power",
        name: "Flower Power",
        
        params: [
          p("size", "Size", "size", 22, 1, 120, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("grain", "Grain", "grain", 52, 0, 100, 1)
        ],
        engine: {
          backend: "pattern",
          strokePath: {"spacing":8,"jitter":15,"scatter":1.2,"streamline":24,"count":2},
          shape: {"type":"square","softness":10,"sizeScale":1},
          grain: {"kind":"paper","depth":0,"scale":1,"rotate":0},
          rendering: {"mode":"marker","wetEdges":false,"flow":100},
          overrides: {"tipScaleStart":1,"tipScaleEnd":1},
        }
      }
    ]
  },
  {
    id: "luminance",
    name: "Luminance",
    brushes: [
      {
        id: "flare",
        name: "Flare",
        
        params: [
          p("size", "Size", "size", 22, 1, 160, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 8, 0, 100, 1)
        ],
        engine: {
          backend: "spray",
          strokePath: {"spacing":3,"jitter":0,"scatter":0,"streamline":24,"count":1},
          shape: {"type":"oval","softness":50,"sizeScale":1},
          grain: {"kind":"none","depth":0,"scale":1},
          rendering: {"mode":"spray","wetEdges":false,"flow":55},
          
        }
      },
      {
        id: "light-pen",
        name: "Light Pen",
        
        params: [
          p("size", "Size", "size", 14, 1, 160, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 8, 0, 100, 1)
        ],
        engine: {
          backend: "spray",
          strokePath: {"spacing":3,"jitter":0,"scatter":0,"streamline":24,"count":1},
          shape: {"type":"oval","softness":50,"sizeScale":1},
          grain: {"kind":"none","depth":0,"scale":1},
          rendering: {"mode":"spray","wetEdges":false,"flow":55},
          
        }
      },
      {
        id: "light-brush",
        name: "Light Brush",
        
        params: [
          p("size", "Size", "size", 26, 1, 160, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 8, 0, 100, 1)
        ],
        engine: {
          backend: "spray",
          strokePath: {"spacing":3,"jitter":0,"scatter":0,"streamline":24,"count":1},
          shape: {"type":"oval","softness":50,"sizeScale":1},
          grain: {"kind":"none","depth":0,"scale":1},
          rendering: {"mode":"spray","wetEdges":false,"flow":55},
          
        }
      },
      {
        id: "pulse",
        name: "Pulse",
        
        params: [
          p("size", "Size", "size", 18, 1, 160, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 8, 0, 100, 1)
        ],
        engine: {
          backend: "spray",
          strokePath: {"spacing":3,"jitter":0,"scatter":0,"streamline":24,"count":1},
          shape: {"type":"oval","softness":50,"sizeScale":1},
          grain: {"kind":"none","depth":0,"scale":1},
          rendering: {"mode":"spray","wetEdges":false,"flow":55},
          
        }
      },
      {
        id: "bokeh-lights",
        name: "Bokeh Lights",
        
        params: [
          p("size", "Size", "size", 24, 1, 160, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 8, 0, 100, 1)
        ],
        engine: {
          backend: "spray",
          strokePath: {"spacing":3,"jitter":0,"scatter":0,"streamline":24,"count":1},
          shape: {"type":"oval","softness":50,"sizeScale":1},
          grain: {"kind":"none","depth":0,"scale":1},
          rendering: {"mode":"spray","wetEdges":false,"flow":55},
          
        }
      },
      {
        id: "light-leaks",
        name: "Light Leaks",
        
        params: [
          p("size", "Size", "size", 26, 1, 160, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 8, 0, 100, 1)
        ],
        engine: {
          backend: "spray",
          strokePath: {"spacing":3,"jitter":0,"scatter":0,"streamline":24,"count":1},
          shape: {"type":"oval","softness":50,"sizeScale":1},
          grain: {"kind":"none","depth":0,"scale":1},
          rendering: {"mode":"spray","wetEdges":false,"flow":55},
          
        }
      },
      {
        id: "glimmer",
        name: "Glimmer",
        
        params: [
          p("size", "Size", "size", 16, 1, 160, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 8, 0, 100, 1)
        ],
        engine: {
          backend: "spray",
          strokePath: {"spacing":3,"jitter":0,"scatter":0,"streamline":24,"count":1},
          shape: {"type":"oval","softness":50,"sizeScale":1},
          grain: {"kind":"none","depth":0,"scale":1},
          rendering: {"mode":"spray","wetEdges":false,"flow":55},
          
        }
      },
      {
        id: "nebula",
        name: "Nebula",
        
        params: [
          p("size", "Size", "size", 28, 1, 160, 1),
          p("flow", "Flow", "flow", 100, 0, 100, 1),
          p("smoothing", "Smoothing", "smoothing", 24, 0, 100, 1),
          p("spacing", "Spacing", "spacing", 8, 0, 100, 1)
        ],
        engine: {
          backend: "spray",
          strokePath: {"spacing":3,"jitter":0,"scatter":0,"streamline":24,"count":1},
          shape: {"type":"oval","softness":50,"sizeScale":1},
          grain: {"kind":"none","depth":0,"scale":1},
          rendering: {"mode":"spray","wetEdges":false,"flow":55},
          
        }
      }
    ]
  }
];

export const BRUSH_BY_ID: Record<string, BrushPreset> = Object.fromEntries(
  BRUSH_CATEGORIES.flatMap((c) => c.brushes.map((b) => [b.id, b]))
);
